import Head from 'next/head'
import { Select, message, Button } from "antd";

const { Option } = Select;

export default function Home() {

  function handleChange(value) {
    console.log(`selected ${value}`);
  }

  const info = () => {
    message.info("This is a normal message");
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline text-blue-800">Hello world!</h1>
      <Select
        defaultValue="lucy"
        style={{ width: 120 }}
        onChange={handleChange}
      >
        <Option value="jack">Jack</Option>
        <Option value="lucy">Lucy</Option>
        <Option value="Yiminghe">yiminghe</Option>
      </Select>

      <Button type="primary" onClick={info}>
        Display normal message
      </Button>
    </div>
  );
}
