import Head from "next/head";
import withAuth from "../hoc/withAuth";
import DashboardLayout from "../components/Layout";
import Dashboard from "../components/Dashboard";
import Customer from "../components/Customer";

function Profile() {
  return (
    <div>
      <Head>
        <title>Profile | Splendid Packaging</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DashboardLayout>
          <Customer />
        </DashboardLayout>
      </main>
    </div>
  );
}

export default withAuth(Profile);
