import Head from "next/head";
import withAuth from "../hoc/withAuth";
import DashboardLayout from "../components/Layout";

function Shipments() {
  return (
    <div>
      <Head>
        <title>Shipments | Splendid Packaging</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <DashboardLayout>
          Hello
        </DashboardLayout>
      </main>
    </div>
  );
}

export default withAuth(Shipments);
